import Header from "./header";
import { Provider } from "../components/Clients";

export const metadata = {
  title: "Yash",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
